// Update Course Information
export const UPDATE_COURSE_NAME = 'UPDATE_COURSE_NAME';
export const UPDATE_COURSE_CREDITS = 'UPDATE_COURSE_CREDITS';
export const UPDATE_COURSE_LETTER_GRADE = 'UPDATE_COURSE_LETTER_GRADE';
export const UPDATE_COURSE_NUMBER_GRADE = 'UPDATE_COURSE_NUMBER_GRADE';
export const UPDATE_COURSE_INCLUDED = 'UPDATE_COURSE_INCLUDED';

// Delete Course
export const DELETE_COURSE = 'DELETE_COURSE';

// Delete Semester
export const DELETE_SEMESTER = 'DELETE_SEMESTER';
